# dACC_HOC35_ventMid.nii / dACC_HOC35_ventMid_rank.csv
daccvm = ['paralimbic',
    'anterior cingulate',
    'pain',
    'cingulate',
    'insula anterior',
    'heat',
    'matrix',
    'acc',
    'fear',
    'middle cingulate',
    'subgenual',
    'brainstem',
    'cingulate cortex',
    'cortex acc',
    'sensations',
    'anterior',
    'negative affect',
    'arousal',
    'painful',
    'anterior insula',
    'regard',
    'skin conductance',
    'circuitry',
    'excessive',
    'conductance',
    'dorsal anterior',
    'neutral pictures',
    'conditioned',
    'amygdala anterior',
    'signature',
    'heart',
    'insula',
    'empathy',
    'focusing',
    'inhibit',
    'regulation',
    'aversive',
    'cortex anterior',
    'female',
    'skin',
    'noxious',
    'somatosensory cortices',
    'electrical',
    'psychophysical',
    'experiencing',
    'prefrontal cortices',
    'periaqueductal',
    'preparation',
    'orbitofrontal cortex',
    'empathic',
    'competing',
    'summary',
    's1',
    'chronic pain',
    'sub',
    'mid',
    'cingulate gyrus',
    'inducing',
    'dose',
    'perfusion',
    'orbitofrontal',
    'reactions',
    'thalamus',
    'heightened',
    'depicting',
    'ratings',
    'regional cerebral',
    'connectivity analyses',
    'nucleus accumbens',
    'lack',
    'cingulate cortices',
    'injury',
    'accumbens',
    'mg',
    'negative correlation',
    'limbic',
    'control groups',
    'ventromedial prefrontal',
    'cortex ba',
    'preliminary',
    'cortex vmpfc',
    'nucleus',
    'cortex lateral',
    'lateral orbitofrontal',
    'engaging',
    'threat',
    'hypothalamus',
    'cortex thalamus',
    'amygdala response',
    'serves',
    'nociceptive',
    'multiple sclerosis',
    'stimulus response',
    'operculum',
    'switch',
    'sustained',
    'rated',
    'cognitive control',
    'anxiety',
    'behaviors']
